#!/home/pi/.virtualenvs/cv/bin/python
from camera import CameraServer
from gpio import GPIOHandler
from tcp_server import PiTCPServer, PiTCPHandler
import threading
import json
from types import SimpleNamespace
import socket
import argparse


class App():

    def __init__(self):
        with open('config.json') as f:
            data = f.read().replace('\n', '')
            config = json.loads(
                data, object_hook=lambda d: SimpleNamespace(**d))
        config.netgear.ip = socket.gethostbyname(config.s_hostname)

        self.camera_server = CameraServer(
            config.camera, config.netgear)
        self.gpio = GPIOHandler(config.gpio, self.camera_server)

        PiTCPServer.allow_reuse_address = True
        self.tcp_server = PiTCPServer(
            self.camera_server, (config.tcp.host, config.tcp.port), PiTCPHandler)

    def run(self, preview):
        if preview:
            while True:
                try:
                    self.camera_server.snap()
                except KeyboardInterrupt:
                    print("Exiting")
                    break
        else:
            while True:
                try:
                    self.tcp_server.serve_forever()
                except KeyboardInterrupt:
                    print("Exiting")
                    break
            t = threading.Thread(target=self.tcp_server.shutdown())
            t.start()
            t.join()

        self.gpio.close()
        self.camera_server.close()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview", nargs="?",
                        type=bool,
                        default=False, const=True)
    args = parser.parse_args()
    app = App()
    app.run(args.preview)


if __name__ == "__main__":
    main()
